### ISSUE TITLE
Error in toGeoJson

### ISSUE THREAD

**Issue by damiles** [databrickslabs/geoscan#62]
Using a basic call:
```python
from geoscan import Geoscan

geoscan = Geoscan() \
.setLatitudeCol('Y') \
.setLongitudeCol('X') \
.setPredictionCol('cluster') \
.setEpsilon(100) \
.setMinPts(40)

points_sampled = data.sample(0.5)
model = geoscan.fit(points_sampled)

model.toGeoJson()
```
we obtain the following error:

```
py4j/protocol.py:326, in get_return_value(answer, gateway_client, target_id, name)
    [324] value = OUTPUT_CONVERTER[type](answer[2:], gateway_client)
    [325] if answer[1] == REFERENCE_TYPE:
--> [326     raise Py4JJavaError(
    [327]         "An error occurred while calling {0}{1}{2}.\n".
    [328]         format(target_id, ".", name), value)
    [329] else:
    [330]     raise Py4JError(
    [331]         "An error occurred while calling {0}{1}{2}. Trace:\n{3}\n".
    [332]         format(target_id, ".", name, value))

Py4JJavaError: An error occurred while calling o227.toGeoJson.
: java.lang.NoSuchMethodError: 'org.json4s.JsonDSL$JsonAssoc org.json4s.JsonDSL$.pair2Assoc(scala.Tuple2, scala.Function1)'
	at com.databricks.labs.gis.ml.package$GeoShape.toGeoJson(package.scala:106)
	at com.databricks.labs.gis.ml.GeoscanModel.toGeoJson(GeoscanModel.scala:45)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at py4j.reflection.MethodInvoker.invoke(MethodInvoker.java:244)
	at py4j.reflection.ReflectionEngine.invoke(ReflectionEngine.java:357)
	at py4j.Gateway.invoke(Gateway.java:282)
	at py4j.commands.AbstractCommand.invokeMethod(AbstractCommand.java:132)
	at py4j.commands.CallCommand.execute(CallCommand.java:79)
	at py4j.ClientServerConnection.waitForCommands(ClientServerConnection.java:182)
	at py4j.ClientServerConnection.run(ClientServerConnection.java:106)
	at java.base/java.lang.Thread.run(Thread.java:829)
```

This issue no affects if we use `GeoscanPersonalized`

**Comment by aamend** [comment]
Weird, I could not reproduce it. `model.toGeoJson()` works for me. 
What DBR version do you use? Did your model yield any cluster?

**Comment by aamend** [comment]
It seems issue is related to 10.4LTS runtime. Solution was designed for 9.1LTS, let me check what's happening

**Comment by damiles** [comment]
I use geoscan as standalon with my spark, and only works with pyspark 3.1.2 and no the newer versions of pyspark because a function is removed `NoSuchMethodError: org.json4s.JsonDSL$JsonAssoc org.json4s.JsonDSL$.pair2Assoc`

**Comment by aamend** [comment]
Should be fixed in geoscan 0.2.8. https://search.maven.org/artifact/com.databricks.labs/geoscan/0.2.8/jar
